### ISSUE TITLE
Retraining Riser for RNA004 dataset

### ISSUE THREAD

**Issue by charlesxu90** [comprna/riser#2]
Dear @EduEyras @a-sneddon ,

I want to retrain Riser for RNA004 dataset. However, I found a parameter that is specific to RNA002/RNA001, that is 'freq = 3012' which determines the length of signals per second. How did you decide this parameter? 

I want to retrain Riser for RNA004. This parameter is mandatory for the retraining. I think it should be different for RNA004.

Thanks in adavance!

**Comment by charlesxu90** [comment]
Here, I suppose that for nanopre, the number of signals per second is fixed, that is 3012. In RNA002, it corresponds around 70 bases, while in RNA004, it corresponds to 120 bases.

So I just use 1s for discrimination, because 2s or more is too many bases for RNA004. Do you think it is okay for Riser?

**Comment by charlesxu90** [comment]
Or RNA004 sequencing is much faster than RNA002. The eject function is now not useful?

**Comment by a-sneddon** [comment]
Hi Charles,

Thanks for your questions!

The “freq = 3012” parameter was set based on the sampling rate (number of current samples measured per second) of the RNA002 system (3012 Hz). For the RNA004 system, this value can be found in the fast5/blow5/pod5 files - I believe it is 4kHz (4000 Hz).

We expect that the benefit of RISER should be amplified with higher throughput sequencing, since RISER will get a chance to act on more molecules. You’re right, however, that the number of seconds of signal that RISER assesses should be less for RNA004 due to the higher translocation rate.

I hope that helps! Let me know if you have any further questions.

Thanks,
Alex

**Comment by charlesxu90** [comment]
Dear @a-sneddon,

Thanks for the reply. I checked the fast5/pod5 file. The sample frequency is 4000. I think using 1s of signals for RNA004 signal decision might be enough, as the quanlity of RNA004 signals is much better. I'll try that. Thanks a lot!

Best regards,
Charles Xu

**Comment by a-sneddon** [comment]
No worries Charles! Good luck!

Thanks,
Alex
